# Generated by Django 3.1.1 on 2020-12-25 09:01

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Absence_presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت حضور')),
            ],
            options={
                'verbose_name': 'حضور غیاب',
                'verbose_name_plural': 'حضور غیاب',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='اعضای کلاس')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='Criticize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='موضوع')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'انتقاد و پیشنهاد',
                'verbose_name_plural': 'انتقادات و پیشنهادات',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='موضوع خبر')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات خبر')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('b', 'پرورشی'), ('e', 'آموزشی')], max_length=1, verbose_name='نوع خبر')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت خبر')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
        migrations.CreateModel(
            name='Paye_abpresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع حضورغیاب')),
                ('date_stop', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پایان حضورغیاب')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت شدن')),
            ],
            options={
                'verbose_name': 'ساخت حضورغیاب',
                'verbose_name_plural': 'ساخت حضورغیاب ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soal', ckeditor.fields.RichTextField(verbose_name='سوال')),
                ('lesson', models.CharField(choices=[('قرآن', 'قرآن'), ('پیام های آسمانی', 'پیام های آسمانی'), ('فارسی', 'فارسی'), ('نگارش', 'نگارش'), ('ریاضی', 'ریاضی'), ('علوم تجربی', 'علوم تجربی'), ('مطالعات اجتماعی', 'مطالعات اجتماعی'), ('فرهنگ و هنر', 'فرهنگ و هنر'), ('عربی', 'عربی'), ('انگلیسی', 'انگلیسی'), ('آمادگی دفاعی', 'آمادگی دفاعی'), ('کار و فناوری', 'کار و فناوری'), ('تفکر و سبک زندگی', 'تفکر و سبک زندگی'), ('تربیت بدنی', 'تربیت بدنی'), ('سایر', 'سایر')], max_length=200, verbose_name='درس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر سوال')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], default='d', max_length=1, verbose_name='وضعیت')),
                ('nomreh', models.FloatField(verbose_name='بارم سوال')),
                ('time', models.FloatField(verbose_name='زمان پاسخ دهی (به دقیقه)')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ طراحی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.class', verbose_name='کلاس پاسخ دهنده')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'بانک سوال',
            },
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='نام کاربر')),
                ('soalid', models.IntegerField(verbose_name='آیدی سوال پاسخ داده شده')),
            ],
            options={
                'verbose_name': 'ثبت سوال',
                'verbose_name_plural': 'ثبت سوالات پاسخ داده شده',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasokh', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر پاسخ')),
                ('nomreh', models.FloatField(blank=True, null=True, verbose_name='نمره این پاسخ')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پاسخ دادن')),
                ('lesson', models.CharField(choices=[('قرآن', 'قرآن'), ('پیام های آسمانی', 'پیام های آسمانی'), ('فارسی', 'فارسی'), ('نگارش', 'نگارش'), ('ریاضی', 'ریاضی'), ('علوم تجربی', 'علوم تجربی'), ('مطالعات اجتماعی', 'مطالعات اجتماعی'), ('فرهنگ و هنر', 'فرهنگ و هنر'), ('عربی', 'عربی'), ('انگلیسی', 'انگلیسی'), ('آمادگی دفاعی', 'آمادگی دفاعی'), ('کار و فناوری', 'کار و فناوری'), ('تفکر و سبک زندگی', 'تفکر و سبک زندگی'), ('تربیت بدنی', 'تربیت بدنی'), ('سایر', 'سایر')], max_length=200, verbose_name='درس')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر پاسخ دهنده')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
            },
        ),
        migrations.CreateModel(
            name='Exam_Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع آزمون')),
                ('date_stop', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پایان آزمون')),
                ('soalat', models.ManyToManyField(to='quiz_app.Question', verbose_name='سوالات')),
            ],
            options={
                'verbose_name': 'زمان بندی آزمون',
                'verbose_name_plural': 'زمان بندی آزمون ها',
            },
        ),
    ]
