# Generated by Django 3.1.1 on 2020-12-30 08:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticize',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات'),
        ),
    ]
