# Generated by Django 3.1.1 on 2020-12-30 08:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20201230_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات خبر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='soal',
            field=tinymce.models.HTMLField(verbose_name='سوال'),
        ),
    ]
