# Generated by Django 3.1.1 on 2021-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20201230_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=1, verbose_name='تعداد لایک ها'),
            preserve_default=False,
        ),
    ]
