# Generated by Django 3.1.1 on 2021-01-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_news_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک ها'),
        ),
    ]
