# Generated by Django 3.1.1 on 2021-01-08 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20210108_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_id', models.IntegerField(verbose_name='آیدی لایک ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر لایک دهنده')),
            ],
            options={
                'verbose_name': 'ثبت  لایک',
                'verbose_name_plural': 'ثبت لایک ها',
            },
        ),
    ]
