# Generated by Django 3.1.1 on 2021-01-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_auto_20210113_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.1.1', verbose_name='آدرس آیپی'),
            preserve_default=False,
        ),
    ]
